export const District = [
  "Bhojpur",
  "Dhankuta",
  "Ilam",
  "Jhapa",
  "Khotang",
  "Morang",
  "Okhaldhunga",
  "Panchthar",
  "Sankhuwasabha",
  "Solukhumbu",
  "Sunsari",
  "Taplejung",
  "Terhathum",
  "Udayapur",
  "Bara",
  "Dhanusa",
  "Mahottari",
  "Parsa",
  "Rautahat",
  "Saptari",
  "Sarlahi",
  "Siraha",
  "Bhaktapur ",
  "Chitwan",
  "Dhading",
  "Dolakha",
  "Kathmandu",
  "Kavrepalanchok",
  "Lalitpur",
  "Makawanpur",
  "Nuwakot ",
  "Ramechhap",
  "Rasuwa",
  "Sindhuli",
  "Sindhupalchok",
  "Baglung",
  "Gorkha",
  "Kaski",
  "Lamjung",
  "Manang",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Parbat",
  "Syangja",
  "Tanahu ",
  "Arghakhanchi",
  "Banke",
  "Bardiya",
  "Dang",
  "Gulmi",
  "Kapilvastu",
  "Parasi",
  "Palpa",
  "Pyuthan",
  "Rolpa",
  "Rukum",
  "Rupandehi",
  "Dailekh ",
  "Dolpa ",
  "Humla ",
  "Jajarkot ",
  "Jumla ",
  "Kalikot ",
  "Mugu ",
  "Rukum Paschim ",
  "Salyan ",
  "Surkhet ",
  "Achham",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Dadeldhura",
  "Darchula",
  "Doti",
  "Kailali",
  "Kanchanpur",
];

export const cardData = [
  {
      id:"1",
      image:require("../assets/img/room.jpg"),
      address:"Devinagar-13,Butwal",
      price:"10000",
  },
  {
    id:"2",
      image:require("../assets/img/room1.jpg"),
      address:"Kalikanagar-12,Butwal",
      price:"10000",
  },
  {
     id:"3",
      image:require("../assets/img/room2.jpg"),
      address:"Sukhanagar-10,Butwal",
      price:"10000",
  },
]
